import { ErrorPopup } from "error.slint";
import { Button, TabWidget, ScrollView } from "std-widgets.slint";
import { FileTabs, FileEntry } from "tabs.slint";

component Landing {
    // In callback
    callback loaded_file;
    update_file := Button {
        text: "Open File";
        clicked => {
            loaded_file();
        }
    }
}

export component AppWindow inherits Window {
    preferred-height: 720px;
    preferred-width: 1280px;
    title: "ORKUM v0.2.0";

    callback open-file-clicked();
    in-out property <[FileEntry]> files: [];
    in-out property <int> active-tab: 0;

    if (root.files.length == 0): Landing {
        loaded_file => {
            root.open-file-clicked();
        }
    }
    if (root.files.length > 0): VerticalLayout {
        padding: 15px;
        spacing: 10px;

        HorizontalLayout {
            spacing: 10px;
            Text {
                text: "Files Open: \{root.files.length}";
                vertical-alignment: center;
            }

            Button {
                text: "Open New File";
                clicked => {
                    root.open-file-clicked()
                }
            }
        }

        tabs:= FileTabs {
            files: files;
        }
    
    }

    callback error_notification <=> error_popup.error_notification;
    error_popup := ErrorPopup {
        height: root.height;
        width: root.width;
    }
}
