import { ScrollView, Button } from "std-widgets.slint";
import { IconButton, Palette } from "util.slint";

export struct FileEntry {
    name: string,
    content: string,
}

component TabHandle {
    // Supplied 
    in property <string> text;
    in property <bool> active;
    callback clicked();
    callback closed();
    Rectangle {
        min-width: 100px;
        max-width: 200px;
        background: active ? ta-handle.pressed ? Palette.accent-700 : (ta-handle.has-hover ? Palette.accent-600 : Palette.accent-500) : ta-handle.has-hover ? Palette.bg-700 : Palette.bg-900;
        border-radius: 4px;
        ta-handle := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                clicked();
            }
        }

        HorizontalLayout {
            padding: 8px;
            padding-right: 4px;
            alignment: space-between;
            Text {
                text: text;
                color: white;
                vertical-alignment: center;
            }

            IconButton {
                src: @image-url("icons/x-mark.svg");
                clicked => {
                    closed();
                }
            }
        }
    }
}

export component FileTabs {
    // Supplied
    in-out property <int> active-tab;
    in-out property <[FileEntry]> files;
    callback close-file(int);
    VerticalLayout {
        padding: 15px;
        spacing: 10px;

        // TODO: Change with TabWidget when dynamic tabs are supported
        HorizontalLayout {
            alignment: start;
            spacing: 5px;
            for entry[i] in root.files: TabHandle {
                text: entry.name;
                active: root.active-tab == i;
                clicked => {
                    root.active-tab = i
                }
                closed => {
                    root.close-file(i);
                }
            }
        }

        Rectangle {
            background: Palette.bg-800;
            border-radius: 4px;
            ScrollView {
                width: root.width - 15px;
                height: root.height - 60px;
                Text {
                    x: 20px;
                    y: 20px;
                    text: root.files[root.active-tab].content;
                    wrap: word-wrap;
                    vertical-alignment: top;
                    horizontal-alignment: left;
                }
            }
        }
    }
}
